### ISSUE TITLE
Please create an AppData file for qtDbf

### ISSUE THREAD

**Issue by hughsie** [Voral/qtDbf#1]
Please consider writing and installing an AppData file with the application description and some screenshots, else qtDbf looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by Voral** [comment]
Thanks. I'll do it

**Comment by Voral** [comment]
AppData file was created

**Comment by hughsie** [comment]
Great, thanks! If you ping me or put a note on this ticket I'll make sure the new release gets quickly into Fedora. Thanks again!
